# Build settings

markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested

root: /octo-5

#Default Settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
