title: Damita Salmon
description: Portfolio / Playhouse
email: omgninjas@me.com
menu:
  - name: About Me
    url: '#about-me'
  - name: Projects
    url: '#projects'
  - name: Contact
    url: '#contact'
seo:
  description: >-
    OMGninjas is a creative studio providing affordable web design services,
    hand-drawn illustration, inappropriate quips and general mockery.
  rel-author: 'https://github.com/omgninjas'
  rel-publisher: 'https://github.com/omgninjas'
google-analytics-ua: UA-64915308-1
blurb: >-
  The bumblebee\'s wings are so thin and it\'s body so big, it should not be
  able to fly. The only problem is, the bee doesn\'t know that. - David Lindsey
skills:
  - name: HTML5 (jade/pug)
    value: '8'
  - name: Python
    value: '4'
  - name: CSS3 (SASS)
    value: '7'
  - name: Gulp/Grunt
    value: '5'
  - name: JS
    value: '7'
  - name: Version Control (Git)
    value: '7'
  - name: Photoshop
    value: '5'
  - name: PHP
    value: '4'
projects:
  - name: Weather App
    folder: proj-1
    file: projects/proj-1.html
  - name: Bootstrap Template
    folder: proj-6
    file: projects/proj-6.html
  - name: JavaScript Calculator
    folder: proj-3
    file: projects/proj-3.html
  - name: HTML Newsletter
    folder: proj-4
    file: projects/proj-4.html
  - name: Tribute Page
    folder: proj-5
    file: projects/proj-5.html
  - name: Random Quote Machine
    folder: proj-2
    file: projects/proj-2.html
  - name: Sign-up Landing
    folder: proj-7
    file: projects/proj-7.html
  - name: Simple Bootstrap Portfolio
    folder: proj-8
    file: projects/proj-8.html
social:
  - icon: twitter
    link: 'http://twitter.com/omgninjaz'
  - icon: github
    link: 'https://github.com/omgninjas'
  - icon: linkedin
    link: 'http://www.linkedin.com/in/damitasalmon/'
  - icon: codepen
    link: 'https://codepen.io/omgninjas'
  - icon: gitlab
    link: 'https://gitlab.com/omgninjas'