title: Damita Salmon
description: Portfolio Playhouse
email: omgninjas@me.com
menu:
  - name: About Me
    url: '#about-me'
  - name: Projects
    url: '#projects'
  - name: Works
    url: '#works'
  - name: Contact
    url: '#contact'
seo:
  description: >-
    OMGninjas is a creative studio providing affordable web design services,
    hand-drawn illustration, inappropriate quips and general mockery.
  rel-author: 'https://plus.google.com/u/0/b/107326198827476542882/107326198827476542882/'
  rel-publisher: 'https://plus.google.com/u/0/b/107326198827476542882/107326198827476542882/'
google-analytics-ua: UA-64915308-1
blurb: >-
  The bumblebee\'s wings are so thin and it\'s body so big, it should not be
  able to fly. The only problem is, the bee doesn\'t know that. - David Lindsey
skills:
  - name: HTML5 (jade/pug)
    value: '8'
  - name: Python
    value: '4'
  - name: CSS3 (SASS)
    value: '7'
  - name: Gulp/Grunt/Webpack
    value: '4'
  - name: JS
    value: '5'
  - name: Version Control (Git)
    value: '5'
  - name: Photoshop
    value: '3'
  - name: Design
    value: '4'
projects:
  - name: Simple Weather App
    folder: proj-1
    file: projects/proj-1.html
  - name: Bootstrap Template
    folder: proj-6
    file: projects/proj-6.html
  - name: JavaScript Calculator
    folder: proj-3
    file: projects/proj-3.html
  - name: PELAvision Newsletter
    folder: proj-4
    file: projects/proj-4.html
  - name: Percy Julian Tribute Page
    folder: proj-5
    file: projects/proj-5.html
  - name: Random Quote Generator
    folder: proj-2
    file: projects/proj-2.html
  - name: Signup Landing Page
    folder: proj-7
    file: projects/proj-7.html
  - name: Simple Portfolio Page
    folder: proj-8
    file: projects/proj-8.html
works:
  - avatar: face-bando.jpg
    name: Stevie Bando
    title: Music Producer
    quote: <p>More information about this project coming soon</p>
    logo: logo1.png
social:
  - icon: twitter
    link: 'http://twitter.com/omgninjaz'
  - icon: github
    link: 'https://github.com/omgninjas'
  - icon: linkedin
    link: 'http://www.linkedin.com/in/damitasalmon/'
  - icon: codepen
    link: 'https://codepen.io/omgninjas'
  - icon: gitlab
    link: 'https://gitlab.com/omgninjas'